@host=https://localhost:5101
@filePath=./test-12345.jpeg

POST {{host}}/upload HTTP/1.1

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

----WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="test-12345.jpeg"
Content-Type: image/jpeg

< {{filePath}}
----WebKitFormBoundary7MA4YWxkTrZu0gW
