@host=https://localhost:5101

### upload file (csv)
POST {{host}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary

----boundary----
Content-Disposition: form-data; name="file"; filename="test.csv"
Content-Type: text/csv

< ./test.csv
----boundary----

### upload file (xml)
POST {{host}}/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----boundary

----boundary
Content-Disposition: form-data; name="file"; filename="test.xml"
Content-Type: text/xml

< ./test.xml
----boundary----
