/*
 Navicat Premium Data Transfer

 Source Server         : local-dev-postgresql
 Source Server Type    : PostgreSQL
 Source Server Version : 120014 (120014)
 Source Host           : localhost:5432
 Source Catalog        : 2c2p_soft_arch_tech_asgmt
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 120014 (120014)
 File Encoding         : 65001

 Date: 05/08/2024 00:45:26
*/


-- ----------------------------
-- Sequence structure for transaction_Id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."transaction_Id_seq";
CREATE SEQUENCE "public"."transaction_Id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER SEQUENCE "public"."transaction_Id_seq" OWNER TO "postgres";

-- ----------------------------
-- Table structure for __EFMigrationsHistory
-- ----------------------------
DROP TABLE IF EXISTS "public"."__EFMigrationsHistory";
CREATE TABLE "public"."__EFMigrationsHistory" (
  "MigrationId" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "ProductVersion" varchar(32) COLLATE "pg_catalog"."default" NOT NULL
)
;
ALTER TABLE "public"."__EFMigrationsHistory" OWNER TO "postgres";

-- ----------------------------
-- Table structure for transaction
-- ----------------------------
DROP TABLE IF EXISTS "public"."transaction";
CREATE TABLE "public"."transaction" (
  "Id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "TransactionId" varchar(50) COLLATE "pg_catalog"."default" NOT NULL,
  "At" timestamp(6) NOT NULL,
  "Currency" varchar(3) COLLATE "pg_catalog"."default" NOT NULL,
  "Status" varchar(1) COLLATE "pg_catalog"."default" NOT NULL,
  "Amount" numeric(18,2) NOT NULL,
  "CreatedAt" timestamp(6) NOT NULL,
  "UpdatedAt" timestamp(6)
)
;
ALTER TABLE "public"."transaction" OWNER TO "postgres";

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."transaction_Id_seq"
OWNED BY "public"."transaction"."Id";
SELECT setval('"public"."transaction_Id_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table __EFMigrationsHistory
-- ----------------------------
ALTER TABLE "public"."__EFMigrationsHistory" ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");

-- ----------------------------
-- Indexes structure for table transaction
-- ----------------------------
CREATE UNIQUE INDEX "IX_transaction_TransactionId" ON "public"."transaction" USING btree (
  "TransactionId" COLLATE "pg_catalog"."default" "pg_catalog"."text_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table transaction
-- ----------------------------
ALTER TABLE "public"."transaction" ADD CONSTRAINT "PK_transaction" PRIMARY KEY ("Id");
