import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import { Kanit } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/providers';
import { PublicEnvScript } from 'next-runtime-env';

const fontKanit = Kanit({
  subsets: ['thai'],
  variable: '--font-kanit',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <PublicEnvScript />
      </head>
      <body
        className={cn(
          'fixed w-full h-full bg-background font-sans antialiased p-0 m-0',
          fontKanit.variable,
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
